import type { FixedCost, TransactionInput } from "@/types";
import { daysInMonth } from "./date";

/**
 * FixedCost を該当月の Transaction 入力に変換する。
 * 該当月に paymentDay が存在しない場合（2/30 等）は月末に丸める。
 */
export function fixedCostToTransactionInput(
  fc: FixedCost,
  monthKey: string,
): TransactionInput {
  const dim = daysInMonth(monthKey);
  const day = Math.min(fc.paymentDay, dim);
  const date = `${monthKey}-${String(day).padStart(2, "0")}`;
  return {
    categoryId: fc.categoryId,
    amount: fc.amount,
    date,
    memo: fc.label ?? "固定費",
    isAutoGenerated: true,
    fixedCostId: fc.id,
  };
}
