"use client";

import { create } from "zustand";
import { persist, createJSONStorage } from "zustand/middleware";
import type {
  Category,
  CategoryInput,
  CategoryTotal,
  FixedCost,
  FixedCostInput,
  MonthlyTotals,
  Transaction,
  TransactionInput,
} from "@/types";
import { DEFAULT_CATEGORIES, STORAGE_KEY, STORAGE_VERSION } from "@/lib/constants";
import { currentMonthKey, monthKeyOf } from "@/lib/date";
import { fixedCostToTransactionInput } from "@/lib/fixedCosts";

function uuid(): string {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return crypto.randomUUID();
  }
  return Math.random().toString(36).slice(2) + Date.now().toString(36);
}

function seedCategories(): Category[] {
  const now = Date.now();
  return DEFAULT_CATEGORIES.map((c, i) => ({
    ...c,
    id: uuid(),
    createdAt: now + i,
  }));
}

interface BudgetStore {
  categories: Category[];
  transactions: Transaction[];
  fixedCosts: FixedCost[];
  selectedMonth: string;
  appliedFixedCostMonths: Record<string, string[]>;

  // Categories
  addCategory: (input: CategoryInput) => Category;
  updateCategory: (id: string, patch: Partial<CategoryInput>) => void;
  removeCategory: (id: string) => void;
  reorderCategories: (ids: string[]) => void;

  // Transactions
  addTransaction: (input: TransactionInput) => Transaction;
  updateTransaction: (id: string, patch: Partial<TransactionInput>) => void;
  removeTransaction: (id: string) => void;

  // FixedCosts
  addFixedCost: (input: FixedCostInput) => FixedCost;
  updateFixedCost: (id: string, patch: Partial<FixedCostInput>) => void;
  removeFixedCost: (id: string) => void;

  // Month
  setSelectedMonth: (monthKey: string) => void;

  // Fixed cost application
  applyFixedCostsForMonth: (monthKey: string) => number;

  // Selectors (recomputed each call)
  getMonthlyTransactions: (monthKey: string) => Transaction[];
  getMonthlyTotals: (monthKey: string) => MonthlyTotals;
  getMonthlyByCategory: (monthKey: string) => CategoryTotal[];
  getCategoryById: (id: string) => Category | undefined;
}

export const useBudgetStore = create<BudgetStore>()(
  persist(
    (set, get) => ({
      categories: seedCategories(),
      transactions: [],
      fixedCosts: [],
      selectedMonth: currentMonthKey(),
      appliedFixedCostMonths: {},

      addCategory: (input) => {
        const cat: Category = {
          ...input,
          id: uuid(),
          sortOrder:
            Math.max(0, ...get().categories.map((c) => c.sortOrder)) + 10,
          createdAt: Date.now(),
        };
        set((s) => ({ categories: [...s.categories, cat] }));
        return cat;
      },

      updateCategory: (id, patch) => {
        set((s) => ({
          categories: s.categories.map((c) =>
            c.id === id ? { ...c, ...patch } : c,
          ),
        }));
      },

      removeCategory: (id) => {
        set((s) => ({
          categories: s.categories.filter((c) => c.id !== id),
          // 関連 Transaction は残す（categoryId は残す = "削除済カテゴリ" として表示）
        }));
      },

      reorderCategories: (ids) => {
        set((s) => {
          const map = new Map(s.categories.map((c) => [c.id, c]));
          const reordered: Category[] = [];
          ids.forEach((id, idx) => {
            const c = map.get(id);
            if (c) reordered.push({ ...c, sortOrder: (idx + 1) * 10 });
          });
          // ids に含まれなかったものは末尾に残す
          for (const c of s.categories) {
            if (!ids.includes(c.id)) reordered.push(c);
          }
          return { categories: reordered };
        });
      },

      addTransaction: (input) => {
        const t: Transaction = {
          id: uuid(),
          categoryId: input.categoryId,
          amount: input.amount,
          date: input.date,
          memo: input.memo,
          receiptImageUrl: input.receiptImageUrl,
          isAutoGenerated: input.isAutoGenerated ?? false,
          fixedCostId: input.fixedCostId,
          createdAt: Date.now(),
        };
        set((s) => ({ transactions: [...s.transactions, t] }));
        return t;
      },

      updateTransaction: (id, patch) => {
        set((s) => ({
          transactions: s.transactions.map((t) =>
            t.id === id ? { ...t, ...patch } : t,
          ),
        }));
      },

      removeTransaction: (id) => {
        set((s) => ({
          transactions: s.transactions.filter((t) => t.id !== id),
        }));
      },

      addFixedCost: (input) => {
        const fc: FixedCost = {
          id: uuid(),
          categoryId: input.categoryId,
          amount: input.amount,
          paymentDay: input.paymentDay,
          label: input.label,
          active: input.active ?? true,
          createdAt: Date.now(),
        };
        set((s) => ({ fixedCosts: [...s.fixedCosts, fc] }));
        return fc;
      },

      updateFixedCost: (id, patch) => {
        set((s) => ({
          fixedCosts: s.fixedCosts.map((f) =>
            f.id === id ? { ...f, ...patch } : f,
          ),
        }));
      },

      removeFixedCost: (id) => {
        set((s) => ({
          fixedCosts: s.fixedCosts.filter((f) => f.id !== id),
          // 生成済 Transaction は残す
        }));
      },

      setSelectedMonth: (monthKey) => set({ selectedMonth: monthKey }),

      applyFixedCostsForMonth: (monthKey) => {
        const { fixedCosts, appliedFixedCostMonths } = get();
        let count = 0;
        for (const fc of fixedCosts.filter((f) => f.active)) {
          const applied = appliedFixedCostMonths[fc.id] ?? [];
          if (applied.includes(monthKey)) continue;
          const input = fixedCostToTransactionInput(fc, monthKey);
          get().addTransaction(input);
          set((s) => ({
            appliedFixedCostMonths: {
              ...s.appliedFixedCostMonths,
              [fc.id]: [...(s.appliedFixedCostMonths[fc.id] ?? []), monthKey],
            },
          }));
          count++;
        }
        return count;
      },

      getMonthlyTransactions: (monthKey) => {
        return get()
          .transactions.filter((t) => monthKeyOf(t.date) === monthKey)
          .sort((a, b) => b.date.localeCompare(a.date));
      },

      getMonthlyTotals: (monthKey) => {
        const txs = get().getMonthlyTransactions(monthKey);
        let expense = 0;
        let income = 0;
        for (const t of txs) {
          const cat = get().categories.find((c) => c.id === t.categoryId);
          if (cat?.type === "income") income += t.amount;
          else expense += t.amount;
        }
        return { expense, income, balance: income - expense };
      },

      getMonthlyByCategory: (monthKey) => {
        const txs = get().getMonthlyTransactions(monthKey);
        const map = new Map<string, number>();
        for (const t of txs) {
          map.set(t.categoryId, (map.get(t.categoryId) ?? 0) + t.amount);
        }
        const rows: CategoryTotal[] = [];
        for (const [categoryId, total] of map) {
          const cat = get().categories.find((c) => c.id === categoryId);
          if (!cat) continue; // 削除済カテゴリは chart で無視
          rows.push({ category: cat, total });
        }
        return rows.sort((a, b) => b.total - a.total);
      },

      getCategoryById: (id) => get().categories.find((c) => c.id === id),
    }),
    {
      name: STORAGE_KEY,
      version: STORAGE_VERSION,
      storage: createJSONStorage(() => localStorage),
      partialize: (state) => ({
        categories: state.categories,
        transactions: state.transactions,
        fixedCosts: state.fixedCosts,
        selectedMonth: state.selectedMonth,
        appliedFixedCostMonths: state.appliedFixedCostMonths,
      }),
    },
  ),
);
