export type CategoryType = "expense" | "income";

export interface Category {
  id: string;
  name: string;
  icon: string;         // Lucide icon 名 e.g. "Utensils"
  color: string;        // "rose" | "amber" | "sky" | ... Tailwind 系
  type: CategoryType;
  isFixedCost: boolean;
  sortOrder: number;
  createdAt: number;
}

export interface Transaction {
  id: string;
  categoryId: string;
  amount: number;               // 円（正の整数）
  date: string;                 // "YYYY-MM-DD"
  memo?: string;
  receiptImageUrl?: string;
  isAutoGenerated: boolean;
  fixedCostId?: string;
  createdAt: number;
}

export interface FixedCost {
  id: string;
  categoryId: string;
  amount: number;
  paymentDay: number;   // 1-31
  label?: string;
  active: boolean;
  createdAt: number;
}

export interface CategoryInput {
  name: string;
  icon: string;
  color: string;
  type: CategoryType;
  isFixedCost: boolean;
}

export interface TransactionInput {
  categoryId: string;
  amount: number;
  date: string;
  memo?: string;
  receiptImageUrl?: string;
  isAutoGenerated?: boolean;
  fixedCostId?: string;
}

export interface FixedCostInput {
  categoryId: string;
  amount: number;
  paymentDay: number;
  label?: string;
  active?: boolean;
}

export interface MonthlyTotals {
  expense: number;
  income: number;
  balance: number;      // income - expense
}

export interface CategoryTotal {
  category: Category;
  total: number;
}
