"use client";

import { X } from "lucide-react";
import { useBudgetStore } from "@/store/useBudgetStore";
import { getIcon } from "@/lib/icons";
import { formatYen } from "@/lib/money";
import { formatDateShort } from "@/lib/date";
import type { Transaction } from "@/types";

interface Props {
  items: Transaction[];
  emptyText?: string;
  onItemClick?: (t: Transaction) => void;
}

export function TransactionList({ items, emptyText, onItemClick }: Props) {
  const getCategoryById = useBudgetStore((s) => s.getCategoryById);
  const removeTransaction = useBudgetStore((s) => s.removeTransaction);

  if (items.length === 0) {
    return (
      <div className="rounded-2xl bg-white/90 border border-pink-100 p-6 text-center text-sm text-stone-400">
        {emptyText ?? "まだ取引がありません"}
      </div>
    );
  }

  return (
    <div className="rounded-2xl bg-white/90 border border-pink-100 overflow-hidden divide-y divide-pink-50">
      {items.map((t) => {
        const cat = getCategoryById(t.categoryId);
        const Icon = getIcon(cat?.icon ?? "HelpCircle");
        const color = cat?.color ?? "slate";
        const isIncome = cat?.type === "income";
        return (
          <div
            key={t.id}
            className="flex items-center gap-3 px-3 py-2.5"
            onClick={() => onItemClick?.(t)}
          >
            <div
              className={`w-10 h-10 rounded-full flex items-center justify-center bg-${color}-100 text-${color}-700`}
            >
              <Icon size={20} />
            </div>
            <div className="flex-1 min-w-0">
              <div className="flex items-baseline gap-2">
                <span className="font-semibold truncate">
                  {cat?.name ?? "削除済カテゴリ"}
                </span>
                {t.isAutoGenerated && (
                  <span className="text-[10px] bg-amber-100 text-amber-700 px-1 rounded">
                    固定費
                  </span>
                )}
              </div>
              <div className="text-xs text-stone-500 truncate">
                {formatDateShort(t.date)}
                {t.memo ? ` · ${t.memo}` : ""}
              </div>
            </div>
            <div
              className={`num font-bold ${
                isIncome ? "text-emerald-600" : "text-stone-900"
              }`}
            >
              {isIncome ? "+" : ""}
              {formatYen(t.amount)}
            </div>
            <button
              type="button"
              className="tap-target -mr-1 p-1 text-stone-400 hover:text-rose-600"
              aria-label="削除"
              onClick={(e) => {
                e.stopPropagation();
                if (confirm("この取引を削除しますか？")) {
                  removeTransaction(t.id);
                }
              }}
            >
              <X size={16} />
            </button>
          </div>
        );
      })}
    </div>
  );
}
